SUBDIRS = 

###### don't modify anything below this line!
BASE = $(shell pwd | sed 's@\(.*\)/seda.*$$@\1/seda@' )
include $(BASE)/Makefile.include

sandStormMgr.class: sandStormConst.class
sandStormProfiler.class: sandStormConst.class
