### Configured to use NBIO by default. If you wish to use JDK 1.4's 
### java.nio package instead, comment out the following line:
SUBDIRS = nbio test
### And then uncomment this line:
#SUBDIRS = nio test

###### don't modify anything below this line!
BASE = $(shell pwd | sed 's@\(.*\)/seda.*$$@\1/seda@' )
include $(BASE)/Makefile.include
